vim.o.cmdheight = 1
vim.o.foldmethod = "indent"
vim.o.foldexpr = ""
vim.o.mouse = ""
vim.o.showtabline = 1
vim.o.splitbelow = false
vim.o.splitright = false
vim.o.timeoutlen = 500
vim.o.shiftwidth = 4
vim.o.tabstop = 4
vim.o.showbreak = "↳ "
vim.o.diffopt = "filler,iwhite,internal,algorithm:patience" -- use patience diff algorithm
