# https://github.com/charliermarsh/ruff#reference
target-version = "py38"
ignore = []
line-length = 80
select = ["E", "F"]

[isort]
known-third-party = []
section-order = [
    "future",
    "standard-library",
    "third-party",
    "first-party",
    "local-folder",
]

[pydocstyle] # https://github.com/charliermarsh/ruff#pydocstyle
convention = "google"
